### ISSUE TITLE
Broken link in Lazy initialisation 

### ISSUE THREAD

**Issue by zmarkan** [mplacona/RealKotlinTips#2]
It points to here: https://realkotlin.com/tutorials/2018-05-03-lazy-initialisation-in-kotlin/%7B%%20post_url%202018-05-01-late-initialisation-in-kotlin%20%%7D

Link is here:
https://github.com/mplacona/RealKotlinTips/blob/1402917eeef59cc7b6b92d43ff64b8bd73365ef0/src/main/kotlin/Examples/LazyInitialisation.kt#L6

;)

**Comment by mplacona** [comment]
This is now fixed. Many thank @zmarkan
